openapi: 3.0.0

info:
  title: LearnMate API
  version: 1.0.0
  description: API for analyzing GitHub and LeetCode profiles.

servers:
  - url: https://learnmate-eiej.onrender.com

paths:

  /analyze-profile:
    post:
      summary: Analyze a student's coding profile
      operationId: analyzeProfile

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                github:
                  type: string
                leetcode:
                  type: string

      responses:
        "200":
          description: Analysis successful